server:
  port: 9090
spring:
  application:
    name: netty-socket-demo
socketio:
  host: localhost
  port: 9091
  maxFramePayloadLength: 1048576  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxHttpContentLength: 1048576 # 设置http交互最大内容长度
  bossCount: 1  # socket连接数大小（如只监听一个端口boss线程组为1即可）
  workCount: 100
  allowCustomRequests: true
  upgradeTimeout: 10000 # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  pingTimeout: 60000  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingInterval: 25000 # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔